STATUS_SUCCESS = 200
STATUS_CONNECTION_FAIL = 501
STATUS_JSON_UNMATCHED = 502
STATUS_OPERATION_UNSUPPORTED = 503
STATUS_PARAMETER_UNMATCHED = 504
STATUS_INFORMATION_INVALID = 505
STATUS_OPERATION_FAILED = 506

PARAMETER_RESULT = 'result'
PARAMETER_STATUS = 'status'
PARAMETER_OPERATION = 'opt'
PARAMETER_INFORMATION = 'info'

GAME_TYPE_BLACKJACK = 1

TRANSACTION_TYPE_RECHARGE = 1;
TRANSACTION_TYPE_BUY = 2;
TRANSACTION_TYPE_TRANSFER = 3;